import type { Atom } from './types'

function formatCoord(value: number): string {
  const text = value.toFixed(3)
  return text.padStart(8, ' ')
}

export function atomsToPdb(atoms: Array<Atom>): string {
  const lines: Array<string> = ['HEADER    GENERATED BY CHEM MODEL EDIT']
  atoms.forEach((atom, index) => {
    const id = String(index + 1).padStart(5, ' ')
    const atomName = atom.symbol.padEnd(3, ' ').padStart(4, ' ')
    const element = atom.symbol.padStart(2, ' ')
    const x = formatCoord(atom.x)
    const y = formatCoord(atom.y)
    const z = formatCoord(atom.z)
    lines.push(
      `ATOM  ${id} ${atomName} UNK A   1    ${x}${y}${z}  1.00  0.00           ${element}`,
    )
  })
  lines.push('END')
  return lines.join('\n')
}
