import { describe, expect, it } from 'vitest'
import fc from 'fast-check'

import { atomsToPdb } from './pdb'

const elementSymbols = [
  'H',
  'He',
  'C',
  'N',
  'O',
  'F',
  'Ne',
  'Na',
  'Mg',
  'Al',
  'Si',
  'P',
  'S',
  'Cl',
  'Ar',
  'K',
  'Ca',
]

const formatCoord = (value: number): string => {
  const text = value.toFixed(3)
  return text.padStart(8, ' ')
}

const atomArb = fc.record({
  symbol: fc.constantFrom(...elementSymbols),
  x: fc.double({ min: -9999, max: 9999, noNaN: true }),
  y: fc.double({ min: -9999, max: 9999, noNaN: true }),
  z: fc.double({ min: -9999, max: 9999, noNaN: true }),
})

describe('atomsToPdb', () => {
  it('formats atoms into PDB lines deterministically', () => {
    fc.assert(
      fc.property(fc.array(atomArb, { maxLength: 25 }), (atoms) => {
        const pdb = atomsToPdb(atoms)
        const lines = pdb.split('\n')

        expect(lines[0]).toBe('HEADER    GENERATED BY CHEM MODEL EDIT')
        expect(lines[lines.length - 1]).toBe('END')
        expect(lines).toHaveLength(atoms.length + 2)

        atoms.forEach((atom, index) => {
          const line = lines[index + 1]
          const id = String(index + 1).padStart(5, ' ')
          const atomName = atom.symbol.padEnd(3, ' ').padStart(4, ' ')
          const element = atom.symbol.padStart(2, ' ')
          const coords = `${formatCoord(atom.x)}${formatCoord(atom.y)}${formatCoord(atom.z)}`

          expect(line.startsWith(`ATOM  ${id} `)).toBe(true)
          expect(line.includes(` ${atomName} `)).toBe(true)
          expect(line.includes(coords)).toBe(true)
          expect(line.endsWith(element)).toBe(true)
        })
      }),
    )
  })
})
